// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: todolist/protobuf/todolist.proto

package todolist

import (
	context "context"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// todolist - 待辦事項
type Todolist struct {
	// ID - 事項ID
	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	// Name - 事項名稱
	Name string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	// Status - 事項狀態
	Status bool `protobuf:"varint,3,opt,name=Status,proto3" json:"Status,omitempty"`
	// MemberId - 會員ID
	MemberId string `protobuf:"bytes,4,opt,name=MemberId,proto3" json:"MemberId,omitempty"`
	// CreatedAt - 建立時間
	CreatedAt            *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Todolist) Reset()         { *m = Todolist{} }
func (m *Todolist) String() string { return proto.CompactTextString(m) }
func (*Todolist) ProtoMessage()    {}
func (*Todolist) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a82c51097bf0c22, []int{0}
}
func (m *Todolist) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Todolist.Unmarshal(m, b)
}
func (m *Todolist) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Todolist.Marshal(b, m, deterministic)
}
func (m *Todolist) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Todolist.Merge(m, src)
}
func (m *Todolist) XXX_Size() int {
	return xxx_messageInfo_Todolist.Size(m)
}
func (m *Todolist) XXX_DiscardUnknown() {
	xxx_messageInfo_Todolist.DiscardUnknown(m)
}

var xxx_messageInfo_Todolist proto.InternalMessageInfo

func (m *Todolist) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Todolist) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Todolist) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *Todolist) GetMemberId() string {
	if m != nil {
		return m.MemberId
	}
	return ""
}

func (m *Todolist) GetCreatedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

// CreateRequest -
type CreateRequest struct {
	// Name - 事項名稱
	Name string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	// MemberId - 會員ID
	MemberId             string   `protobuf:"bytes,2,opt,name=MemberId,proto3" json:"MemberId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a82c51097bf0c22, []int{1}
}
func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateRequest) GetMemberId() string {
	if m != nil {
		return m.MemberId
	}
	return ""
}

// DeleteRequest -
type DeleteRequest struct {
	// ID - 事項ID
	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	// MemberId - 會員ID
	MemberId             string   `protobuf:"bytes,2,opt,name=MemberId,proto3" json:"MemberId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a82c51097bf0c22, []int{2}
}
func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *DeleteRequest) GetMemberId() string {
	if m != nil {
		return m.MemberId
	}
	return ""
}

// GetRequest -
type GetRequest struct {
	// MemberId - 會員ID
	MemberId             string   `protobuf:"bytes,1,opt,name=MemberId,proto3" json:"MemberId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a82c51097bf0c22, []int{3}
}
func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetMemberId() string {
	if m != nil {
		return m.MemberId
	}
	return ""
}

// UpdateRequest -
type UpdateRequest struct {
	// ID - 事項ID
	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	// MemberId - 會員ID
	MemberId             string   `protobuf:"bytes,2,opt,name=MemberId,proto3" json:"MemberId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a82c51097bf0c22, []int{4}
}
func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(m, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *UpdateRequest) GetMemberId() string {
	if m != nil {
		return m.MemberId
	}
	return ""
}

// CreateResponse -
type CreateResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a82c51097bf0c22, []int{5}
}
func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (m *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(m, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

// DeleteResponse -
type DeleteResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a82c51097bf0c22, []int{6}
}
func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(m, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

// GetResponse -
type GetResponse struct {
	TodoList             []*Todolist `protobuf:"bytes,1,rep,name=todoList,proto3" json:"todoList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a82c51097bf0c22, []int{7}
}
func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetTodoList() []*Todolist {
	if m != nil {
		return m.TodoList
	}
	return nil
}

// UpdateResponse -
type UpdateResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateResponse) Reset()         { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()    {}
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a82c51097bf0c22, []int{8}
}
func (m *UpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateResponse.Unmarshal(m, b)
}
func (m *UpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateResponse.Marshal(b, m, deterministic)
}
func (m *UpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateResponse.Merge(m, src)
}
func (m *UpdateResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateResponse.Size(m)
}
func (m *UpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Todolist)(nil), "todolist.todolist")
	proto.RegisterType((*CreateRequest)(nil), "todolist.CreateRequest")
	proto.RegisterType((*DeleteRequest)(nil), "todolist.DeleteRequest")
	proto.RegisterType((*GetRequest)(nil), "todolist.GetRequest")
	proto.RegisterType((*UpdateRequest)(nil), "todolist.UpdateRequest")
	proto.RegisterType((*CreateResponse)(nil), "todolist.CreateResponse")
	proto.RegisterType((*DeleteResponse)(nil), "todolist.DeleteResponse")
	proto.RegisterType((*GetResponse)(nil), "todolist.GetResponse")
	proto.RegisterType((*UpdateResponse)(nil), "todolist.UpdateResponse")
}

func init() { proto.RegisterFile("todolist/protobuf/todolist.proto", fileDescriptor_3a82c51097bf0c22) }

var fileDescriptor_3a82c51097bf0c22 = []byte{
	// 355 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0xed, 0xa6, 0xb5, 0xb4, 0x53, 0x5a, 0x64, 0xf0, 0x63, 0xc9, 0xc5, 0x90, 0x53, 0x4e, 0x29,
	0x54, 0x0f, 0x82, 0x14, 0x11, 0x0b, 0xa5, 0xa0, 0x1e, 0xa2, 0xfe, 0x80, 0x94, 0x8c, 0xa5, 0xd0,
	0xb8, 0xb1, 0xbb, 0xfd, 0x37, 0xfe, 0x51, 0x6f, 0x92, 0xdd, 0x6e, 0xb2, 0x69, 0xc1, 0x83, 0xb7,
	0x9d, 0xb7, 0x6f, 0xe6, 0xbd, 0x37, 0xbb, 0x10, 0x28, 0x91, 0x89, 0xcd, 0x5a, 0xaa, 0x71, 0xb1,
	0x15, 0x4a, 0x2c, 0x77, 0x1f, 0x63, 0x8b, 0xc4, 0x1a, 0xc1, 0x9e, 0xad, 0xfd, 0xab, 0x95, 0x10,
	0xab, 0x0d, 0x39, 0xcc, 0x75, 0x4e, 0x52, 0xa5, 0x79, 0x61, 0xa8, 0xe1, 0x37, 0x83, 0x8a, 0x8d,
	0x23, 0xf0, 0x16, 0x33, 0xce, 0x02, 0x16, 0xf5, 0x13, 0x6f, 0x31, 0x43, 0x84, 0xce, 0x4b, 0x9a,
	0x13, 0xf7, 0x34, 0xa2, 0xcf, 0x78, 0x01, 0xdd, 0x57, 0x95, 0xaa, 0x9d, 0xe4, 0xed, 0x80, 0x45,
	0xbd, 0x64, 0x5f, 0xa1, 0x0f, 0xbd, 0x67, 0xca, 0x97, 0xb4, 0x5d, 0x64, 0xbc, 0xa3, 0xf9, 0x55,
	0x8d, 0xb7, 0xd0, 0x7f, 0xdc, 0x52, 0xaa, 0x28, 0x7b, 0x50, 0xfc, 0x24, 0x60, 0xd1, 0x60, 0xe2,
	0xc7, 0xc6, 0x59, 0x6c, 0x9d, 0xc5, 0x6f, 0xd6, 0x59, 0x52, 0x93, 0xc3, 0x7b, 0x18, 0x9a, 0x22,
	0xa1, 0xaf, 0x1d, 0x49, 0x55, 0x59, 0x62, 0x8e, 0x25, 0x57, 0xda, 0x6b, 0x4a, 0x87, 0x77, 0x30,
	0x9c, 0xd1, 0x86, 0xea, 0x01, 0x87, 0x19, 0xff, 0x6a, 0x8e, 0x00, 0xe6, 0xa4, 0x6c, 0xa7, 0xcb,
	0x64, 0xc7, 0x32, 0xef, 0x45, 0x96, 0xfe, 0x4f, 0xe6, 0x14, 0x46, 0x36, 0xa4, 0x2c, 0xc4, 0xa7,
	0xa4, 0x12, 0xb1, 0xae, 0xf7, 0xc8, 0x14, 0x06, 0xda, 0x8a, 0x29, 0x31, 0x36, 0xaf, 0xf6, 0xb4,
	0x96, 0x8a, 0xb3, 0xa0, 0x1d, 0x0d, 0x26, 0x18, 0x57, 0x9f, 0xc0, 0x1e, 0x92, 0x8a, 0x53, 0x0e,
	0xb4, 0xfe, 0xcc, 0x84, 0xc9, 0x0f, 0x83, 0x4e, 0x79, 0x8d, 0x53, 0xe8, 0x1a, 0x75, 0xbc, 0xac,
	0x47, 0x34, 0x96, 0xee, 0xf3, 0xe3, 0x8b, 0xbd, 0xad, 0x56, 0xd9, 0x6e, 0xac, 0xba, 0xed, 0x8d,
	0x95, 0xbb, 0xed, 0x07, 0xa9, 0x5a, 0x78, 0x03, 0xed, 0x39, 0x29, 0x3c, 0xab, 0x29, 0xf5, 0xc6,
	0xfd, 0xf3, 0x03, 0xd4, 0x15, 0x35, 0x71, 0x5c, 0xd1, 0xc6, 0x03, 0xb8, 0xa2, 0xcd, 0xe4, 0x61,
	0x6b, 0xd9, 0xd5, 0x9f, 0xee, 0xfa, 0x37, 0x00, 0x00, 0xff, 0xff, 0xa9, 0xe1, 0x9a, 0x48, 0x4a,
	0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TodoClient is the client API for Todo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TodoClient interface {
	// Create - 新增事項
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	// Delete - 刪除事項
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	// Get - 取得事項
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	// Update - 完成事項
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
}

type todoClient struct {
	cc *grpc.ClientConn
}

func NewTodoClient(cc *grpc.ClientConn) TodoClient {
	return &todoClient{cc}
}

func (c *todoClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, "/todolist.todo/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, "/todolist.todo/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/todolist.todo/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, "/todolist.todo/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TodoServer is the server API for Todo service.
type TodoServer interface {
	// Create - 新增事項
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
	// Delete - 刪除事項
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	// Get - 取得事項
	Get(context.Context, *GetRequest) (*GetResponse, error)
	// Update - 完成事項
	Update(context.Context, *UpdateRequest) (*UpdateResponse, error)
}

// UnimplementedTodoServer can be embedded to have forward compatible implementations.
type UnimplementedTodoServer struct {
}

func (*UnimplementedTodoServer) Create(ctx context.Context, req *CreateRequest) (*CreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedTodoServer) Delete(ctx context.Context, req *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (*UnimplementedTodoServer) Get(ctx context.Context, req *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedTodoServer) Update(ctx context.Context, req *UpdateRequest) (*UpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}

func RegisterTodoServer(s *grpc.Server, srv TodoServer) {
	s.RegisterService(&_Todo_serviceDesc, srv)
}

func _Todo_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todolist.todo/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Todo_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todolist.todo/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Todo_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todolist.todo/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Todo_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todolist.todo/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Todo_serviceDesc = grpc.ServiceDesc{
	ServiceName: "todolist.todo",
	HandlerType: (*TodoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Todo_Create_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Todo_Delete_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Todo_Get_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Todo_Update_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "todolist/protobuf/todolist.proto",
}
